name: Preset generator

on: 
  workflow_dispatch:
    inputs:
      frame_size:
        description: "Оберіть для якого дрона (F7..F11)"
        type: choice
        options: 
        - F7
        - F10
        required: true
        default: "f7"
      flight_controller:
        description: "Оберіть для якого польотного контролера ..."
        type: choice
        options: 
        - rush
        - diatone
        - geprc
        required: true
        default: "rush"
      vtx_type:
        description: "Оберіть частоту відео передавача (1.3 .. 5.8)"
        type: choice
        options: 
        - "5.8"
        - "1.3"
        - "4.9"
        required: true
        default: "5.8"
      is_thermal:
        description: "Камера тепловізійна"
        type: boolean
        default: false
      vtx_name:
        description: "Оберіть відео передавач ..."
        type: choice
        options: 
        - max_solo
        - max_solo_x
        - geprc
        - rush
        required: true
        default: "max_solo"
      custom_osd:
        description: "Тестова ОСД ..."
        type: boolean
        default: false
    
      
jobs:
  merge-texts:
    runs-on: ubuntu-latest 
    env:
       FILE_NAME: ${{inputs.frame_size}}_${{inputs.flight_controller}}_${{inputs.vtx_name}}.txt 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Upload header to the file
        run: |
          HEADER=$(cat header.txt)
          echo "$HEADER" >> ${{ env.FILE_NAME }} 

      - name: Upload FC related setup
        run: | 
          FC_BLOCK=$(cat FC/${{inputs.flight_controller}}.txt)
          echo "$FC_BLOCK" >> ${{ env.FILE_NAME }}
      
      - name: Upload Master table to the file
        run: |
          MASTER_TABLE=$(cat PIDs/${{inputs.frame_size}}.txt)
          echo "$MASTER_TABLE" >> ${{ env.FILE_NAME }} 
          echo "set craft_name = ${{inputs.frame_size}}" >> ${{ env.FILE_NAME }}
    
      - name: Update if thermal 
        if: ${{inputs.is_thermal}}
        run: |
          echo "set craft_name = ${{inputs.frame_size}}T" >> ${{ env.FILE_NAME }}

      - name: Upload OSD table to the file    
        if: ${{ inputs.custom_osd }}
        run: |
          OSD=$(cat OSD/custom_osd.txt)
          echo "$OSD" >> ${{ env.FILE_NAME }}

      - name: Upload OSD table to the file    
        if: ${{ !inputs.custom_osd }}
        run: |
          OSD=$(cat OSD/default_osd.txt)
          echo "$OSD" >> ${{ env.FILE_NAME }}

      - name: Upload VTX block to the file
        run: |
          VTX_BLOCK=$(cat vtx_tables/${{inputs.vtx_type}}/vtx_block.txt)
          echo "$VTX_BLOCK" >> ${{ env.FILE_NAME }} 
      
      - name: Upload VTX table to the file
        run: |
          VTX_TABLE=$(cat vtx_tables/${{inputs.vtx_type}}/${{inputs.vtx_name}}.txt)
          echo "$VTX_TABLE" >> ${{ env.FILE_NAME }} 
   
      - name: Upload footer to the file
        run: |
          FOOTER=$(cat footer.txt)
          echo "$FOOTER" >> ${{ env.FILE_NAME }}
          
      - name: Post the results
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.FILE_NAME }} 
