name: Preset generator

on: 
  workflow_dispatch:
    inputs:
      frame_size:
        description: "Оберіть для якого дрона (F7..F11)"
        type: choice
        options: 
        - F7
        - F8
        - F9
        - F10
        - F11
        required: true
        default: "f7"
      flight_controller:
        description: "Оберіть для якого польотного контролера ..."
        type: choice
        options: 
        - rush
        - diatone
        - geprc
        required: true
        default: "rush"
      vtx_type:
        description: "Оберіть частоту відео передавача (1.3 .. 5.8)"
        type: choice
        options: 
        - "5.8"
        - "1.3"
        - "2.4"
        - "3.3"
        required: true
        default: "5.8"
      vtx_name:
        description: "Оберіть відео передавач ..."
        type: choice
        options: 
        - max_solo
        - geprc
        required: true
        default: "ft"
      custom_osd:
        description: "Тестова ОСД ..."
        type: boolean
        default: false
      
jobs:
  merge-texts:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new preset file name
        run: |
          FILE_NAME=${{inputs.frame_size}}_${{inputs.flight_controller}}_${{inputs.vtx_name}}.txt 
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        
      - name: Upload header to the file
        run: |
          HEADER=$(cat header.txt)
          echo "$HEADER" >> ${{ env.FILE_NAME }} 

      - name: Upload Master table to the file
        run: |
          MASTER_TABLE=$(cat PIDs/${{inputs.frame_size}}.txt)
          echo "$MASTER_TABLE" >> ${{ env.FILE_NAME }} 
          echo "set craft_name = ${{inputs.frame_size}}" >> ${{ env.FILE_NAME }}

      - name: Upload OSD table to the file        
        run: |
          if [[ ${{ inputs.custom_osd }} ]]; then
            echo $(cat OSD/custom_osd.txt) >> ${{ env.FILE_NAME }}
          else
            echo $(cat OSD/default_osd.txt) >> ${{ env.FILE_NAME }}
          fi
          
      - name: Upload VTX table to the file
        run: |
          VTX_TABLE=$(cat vtx_tables/${{inputs.vtx_type}}/${{inputs.vtx_name}}.txt)
          echo "$VTX_TABLE" >> ${{ env.FILE_NAME }} 

      - name: Upload VTX block to the file
        run: |
          VTX_BLOCK=$(cat vtx_tables/${{inputs.vtx_type}}/vtx_block.txt)
          echo "$VTX_BLOCK" >> ${{ env.FILE_NAME }} 

      - name: Upload footer to the file
        run: |
          FOOTER=$(cat footer.txt)
          echo "$FOOTER" >> ${{ env.FILE_NAME }}
          
      - name: Post the results
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: ${{ env.FILE_NAME }} 

          
