name: Test text marging

on: 
  workflow_dispatch:
    inputs:
      frame_size:
        description: "Select Frame size (F7..F11)"
        type: choice
        options: 
        - f7
        - f8
        - f9
        - f10
        - f11
        required: true
        default: "f7"
      flight_controller:
        description: "Select Flight controller"
        type: choice
        options: 
        - rush
        - diatone
        - geprc
        required: true
        default: "rush"
      vtx_type:
        description: "Select VTX type (1.3 .. 5.8)"
        type: choice
        options: 
        - 5,8
        - 1,3
        - 2,4
        - 3,3
        required: true
        default: "5,8"
      vtx_name:
        description: "Select VTX name"
        type: choice
        options: 
        - ft
        - rush
        - geprc
        required: true
        default: "ft"
      
jobs:
  merge-texts:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Read file contents
        run: |
          CONTENT=$(cat vtx_tables/rush.txt)
          echo "$CONTENT" > test.txt
        
      - name: Printing text
        run: |
          echo "##########################################################################################" >> test.txt
          echo "##########################################################################################" >> test.txt
          echo "######################### Welcome to FLASH TECH preset generator #########################" >> test.txt


          echo "Here is your choice:" >> test.txt
          echo "You need some awesome preset For the ${{inputs.frame_size}} drone" >> test.txt
          echo "with the ${{inputs.flight_controller}} stack and with" >> test.txt
          echo "with the ${{inputs.vtx_name}} video transmitter!" >> test.txt
          
      - name: Post the results
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: test.txt
          
