name: Test text marging

on: 
  workflow_dispatch:
    inputs:
      frame_size:
        description: "Select Frame size (F7..F11)"
        type: choice
        options: 
        - f7
        - f8
        - f9
        - f10
        - f11
        required: true
        default: "f7"
      flight_controller:
        description: "Select Flight controller"
        type: choice
        options: 
        - rush
        - diatone
        - geprc
        required: true
        default: "rush"
      vtx_type:
        description: "Select VTX type (1.3 .. 5.8)"
        type: choice
        options: 
        - 5,8
        - 1,3
        - 2,4
        - 3,3
        required: true
        default: "5,8"
      vtx_name:
        description: "Select VTX name"
        type: choice
        options: 
        - ft
        - rush
        - geprc
        required: true
        default: "ft"
      
jobs:
  merge-texts:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new preset file name
        run: |
          FILE_NAME=${{inputs.frame_size}}_${{inputs.flight_controller}}_${{inputs.vtx_name}}.txt 
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
        
      - name: Upload header to the file
        run: |
          HEADER=$(cat header.txt)
          echo "$HEADER" > $FILE_NAME 
          
      - name: Post the results
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: $FILE_NAME
          
